//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tea
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public short Qty { get; set; }
        public double Price { get; set; }
        public string Year { get; set; }
    }
}
