//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleWCFService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tea", Namespace="http://schemas.datacontract.org/2004/07/ConsoleWCFService")]
    public partial class Tea : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private string NameField;
        
        private double PriceField;
        
        private short QtyField;
        
        private string TypeField;
        
        private string YearField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Qty
        {
            get
            {
                return this.QtyField;
            }
            set
            {
                this.QtyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Year
        {
            get
            {
                return this.YearField;
            }
            set
            {
                this.YearField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://wakeupbuytea.com", ConfigurationName="ITeaStore")]
public interface ITeaStore
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://wakeupbuytea.com/ITeaStore/GetTeaInfo", ReplyAction="http://wakeupbuytea.com/ITeaStore/GetTeaInfoResponse")]
    string GetTeaInfo(string teaName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://wakeupbuytea.com/ITeaStore/GetTeaInfo", ReplyAction="http://wakeupbuytea.com/ITeaStore/GetTeaInfoResponse")]
    System.Threading.Tasks.Task<string> GetTeaInfoAsync(string teaName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://wakeupbuytea.com/ITeaStore/GetTeaNames", ReplyAction="http://wakeupbuytea.com/ITeaStore/GetTeaNamesResponse")]
    string GetTeaNames();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://wakeupbuytea.com/ITeaStore/GetTeaNames", ReplyAction="http://wakeupbuytea.com/ITeaStore/GetTeaNamesResponse")]
    System.Threading.Tasks.Task<string> GetTeaNamesAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://wakeupbuytea.com/ITeaStore/GetAllTeas", ReplyAction="http://wakeupbuytea.com/ITeaStore/GetAllTeasResponse")]
    ConsoleWCFService.Tea[] GetAllTeas();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://wakeupbuytea.com/ITeaStore/GetAllTeas", ReplyAction="http://wakeupbuytea.com/ITeaStore/GetAllTeasResponse")]
    System.Threading.Tasks.Task<ConsoleWCFService.Tea[]> GetAllTeasAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ITeaStoreChannel : ITeaStore, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class TeaStoreClient : System.ServiceModel.ClientBase<ITeaStore>, ITeaStore
{
    
    public TeaStoreClient()
    {
    }
    
    public TeaStoreClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public TeaStoreClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TeaStoreClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TeaStoreClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetTeaInfo(string teaName)
    {
        return base.Channel.GetTeaInfo(teaName);
    }
    
    public System.Threading.Tasks.Task<string> GetTeaInfoAsync(string teaName)
    {
        return base.Channel.GetTeaInfoAsync(teaName);
    }
    
    public string GetTeaNames()
    {
        return base.Channel.GetTeaNames();
    }
    
    public System.Threading.Tasks.Task<string> GetTeaNamesAsync()
    {
        return base.Channel.GetTeaNamesAsync();
    }
    
    public ConsoleWCFService.Tea[] GetAllTeas()
    {
        return base.Channel.GetAllTeas();
    }
    
    public System.Threading.Tasks.Task<ConsoleWCFService.Tea[]> GetAllTeasAsync()
    {
        return base.Channel.GetAllTeasAsync();
    }
}
