//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CA2_Azure.Models
{
    using ServiceLayer;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    // added TeaMetaData class for model validation, because partial class will be rewritten each time
    // if there is a change in designer

    [MetadataType(typeof(TeaMetaData))]
    public partial class Tea
    {
        
        public int Id { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public short Qty { get; set; }
        public double Price { get; set; }
        public string Year { get; set; }
    }


}
